language: ruby
script: bin/run_specs.sh
rvm:
  - 2.2
  - 2.1
  - 2.0
  - 1.9
  - jruby
  - rbx
branches:
  only: master
env:
  global:
    - CODECLIMATE_REPO_TOKEN=1e88b3c41713520cf916ba011dad063d420f98fddd64c8b081850aba9ebcae2e
