language: ruby
script: bin/run_specs.sh
rvm:
  - 2.1
  - 2.0
  - 1.9
  - jruby
  - rbx
branches:
  only: master
env:
  global:
    secure: CrU4e01+yfyszZ8DYBdrqq/kCzuWif4wezsPtrjJuQEnm158KVRgjxIU9GrFqJeus7gsMFb4E/FWrTxMjsqe84l2pppAoEMz04ckktDL+Hck8aOIuR77Q9VbFqaEYc/2fNbLCNIGoIDu7g1lmJZvW46BlwALBPNMcMvpyjY7DII=
